name: "Date Action"
description: "Outputs today's day and date"
author: "Jyotirmay Sarna"

#	This is a Node.js action, which runs index.js
runs:
  using: "node20"
  main: "index.js"

# It exposes an output called today
outputs:
  today:
    description: "Today's formatted day and date"
